# Generated by Django 3.0.8 on 2021-06-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210607_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='country',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='person',
            name='aboutskills',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='About Skills'),
        ),
        migrations.AlterField(
            model_name='person',
            name='bio',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Describe yourself'),
        ),
        migrations.AlterField(
            model_name='person',
            name='biopro',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Your Vision'),
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
